{% set name = "wagtail-storages" %}
{% set version = "2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ba3da585d4ffeb8acd828adbed905cbe3db1e799d41318afbd953a472afd1b38

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - django >=4.2
    - python >={{ python_min }}
    - wagtail >=5.2
    - django-storages <2

test:
  imports:
    - wagtail_storages
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/torchbox/wagtail-storages
  summary: Use AWS S3 with private documents in Wagtail.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
